default:
  image: golang:1.15

stages:
- test
- build
- pages

test:
  except: 
    - schedules
  stage: test
  script:
    - go test -v ./...
build:
  only: 
    - tags
  stage: build
  script: 
    - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations
    - export GITHUB_TOKEN=$GITHUB_TOKEN && curl -sL https://git.io/goreleaser | bash

pages:
  script:
    - chmod +x godownloader.sh
    - ./godownloader.sh -d
    - git clone --depth 1 https://gitlab.com/n8225/awesome-selfhosted.git --branch master --single-branch /tmp/awesome-selfhosted
    - rm list/*
    - ./bin/awesome-selfhosted-gen --path /tmp/awesome-selfhosted/README.md --ghtoken $GITHUB_TOKEN
    - git clone --depth 1 --single-branch --branch gh-pages https://n8225:$GITHUB_TOKEN@github.com/n8225/awesome-selfhosted-gen.git public
    - cd public
    - rm -rf static
    - mv ../index.html . && mv ../static static
    - git config user.email "n8225@gmail.com" && git config user.name "Nathan"
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
  artifacts:
    paths:
    - public
  only: 
    - schedules